import { useState, useEffect } from "react";
import {
    BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer
} from "recharts";
import { Activity, Code, Award, Flame, Zap, Search, Star, Shield, ExternalLink } from "lucide-react";
import { motion } from "framer-motion";
import { Link } from 'react-router-dom';

export default function HackerCockpit() {
    const [inputTeamName, setInputTeamName] = useState("");
    const [activeTeam, setActiveTeam] = useState("");
    const [githubData, setGithubData] = useState(null);
    const [aiData, setAiData] = useState(null);
    const [sparksMap, setSparksMap] = useState({});
    const [repoUrl, setRepoUrl] = useState("");
    const [syncing, setSyncing] = useState(false);
    const [syncMsg, setSyncMsg] = useState("");

    useEffect(() => {
        if (!activeTeam) return;
        // Fetch real stats from the backend generated by Octokit and Groq
        const fetchStats = async () => {
            try {
                const res = await fetch(`/github/stats/${activeTeam}`);
                if (res.ok) {
                    const data = await res.json();

                    // Gamification Update: Rank contributors by actual features built first, then raw commits
                    const sortedContributors = (data.contributors || []).sort((a, b) => {
                        const aFeatures = a.featuresBuilt?.length || 0;
                        const bFeatures = b.featuresBuilt?.length || 0;
                        if (bFeatures !== aFeatures) return bFeatures - aFeatures;
                        return b.commits - a.commits;
                    });

                    setGithubData({
                        contributors: sortedContributors,
                        totalCommits: data.totalCommits || 0,
                        branches: data.branches || [],
                        languages: data.languages || {}
                    });
                    setAiData({
                        implementedFeatures: data.implementedFeatures || [],
                        missingPitchedFeatures: data.missingPitchedFeatures || [],
                        relevanceScore: data.relevanceScore || 0,
                        summary: data.summary || null
                    });
                }
            } catch (err) {
                console.error("Failed to fetch cockpit stats", err);
            }
        };
        fetchStats();
        // Optional: poll every 15s to update radar when sync completes
        const intervalId = setInterval(fetchStats, 15000);
        return () => clearInterval(intervalId);
    }, [activeTeam]);

    const handleSpark = async (contributorAuthor) => {
        try {
            const res = await fetch(`/test/mock-spark/${contributorAuthor}`, { method: "POST" });
            const data = await res.json();
            setSparksMap(prev => ({ ...prev, [contributorAuthor]: data.newTotal }));
        } catch (e) {
            console.error(e);
        }
    };

    const handleRepoSync = async () => {
        if (!repoUrl || !inputTeamName) {
            setSyncMsg("⚠️ Please enter both Team Name and Repository URL");
            return;
        }
        setSyncing(true);
        setSyncMsg("");
        try {
            const res = await fetch(`/github/sync/${inputTeamName}`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ teamName: inputTeamName, githubUrl: repoUrl })
            });
            if (res.ok) {
                setSyncMsg("✅ Repository Synced! Codebase AI Scan Complete.");
                setActiveTeam(inputTeamName);
            } else {
                const errData = await res.json().catch(() => ({}));
                setSyncMsg(`⚠️ Sync failed: ${errData.message || "Unknown error (check terminal)"}`);
            }
        } catch (e) {
            setSyncMsg("❌ Cannot reach backend sync API.");
        }
        setSyncing(false);
    };

    const hasStats = githubData && aiData && githubData.contributors.length > 0;
    const topCoder = hasStats ? githubData.contributors.reduce((prev, curr) => (prev.commits > curr.commits) ? prev : curr, githubData.contributors[0]) : null;

    return (
        <div className="min-h-screen bg-gray-950 text-white p-8">
            <header className="mb-10 text-center">
                <h1 className="text-4xl font-extrabold tracking-widest text-[#9FEF00]">
                    HACKER COCKPIT
                </h1>
                <p className="text-gray-400 mt-2 text-lg uppercase">
                    {activeTeam ? `Team: ${activeTeam} // Live Orbit Telemetry` : "Connect to a Team to Monitor Telemetry"}
                </p>
            </header>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">

                {/* Left Column: AI Feature Progress */}
                <div className="lg:col-span-1 space-y-8">

                    {/* Repository Submission Box */}
                    <div className="bg-gray-900 border border-blue-500/30 p-6 rounded-2xl shadow-2xl relative overflow-hidden">
                        <h2 className="text-xl font-bold mb-3 text-blue-400 flex items-center gap-2">🔗 Link Repository</h2>
                        <p className="text-sm text-gray-400 mb-4">Enter Team Name and submit your GitHub URL to trigger the Codebase Audit.</p>

                        <div className="flex gap-2 mb-3">
                            <input
                                type="text"
                                value={inputTeamName}
                                onChange={(e) => setInputTeamName(e.target.value)}
                                placeholder="Team Name (e.g., Apollo)"
                                className="w-full bg-gray-950 border border-gray-700 rounded-lg px-4 py-3 text-white outline-none focus:border-blue-500 transition-colors"
                            />
                            <button
                                onClick={() => setActiveTeam(inputTeamName)}
                                disabled={!inputTeamName || syncing}
                                className="bg-gray-800 hover:bg-gray-700 px-4 py-3 rounded-lg border border-gray-700 transition"
                                title="Load Existing Telemetry"
                            >
                                <Search size={20} className="text-blue-400" />
                            </button>
                        </div>

                        <input
                            type="text"
                            value={repoUrl}
                            onChange={(e) => setRepoUrl(e.target.value)}
                            placeholder="https://github.com/team/repo"
                            className="w-full bg-gray-950 border border-gray-700 rounded-lg px-4 py-3 mb-3 text-white outline-none focus:border-blue-500 transition-colors"
                        />
                        <button
                            onClick={handleRepoSync}
                            disabled={syncing || !repoUrl || !inputTeamName}
                            className="w-full bg-blue-600 hover:bg-blue-500 text-white font-bold py-3 rounded-lg disabled:opacity-50 transition-colors"
                        >
                            {syncing ? "📡 Syncing Codebase..." : "Initiate AI Codebase Scan"}
                        </button>
                        {syncMsg && <p className={`mt-3 text-sm ${syncMsg.includes('✅') ? 'text-green-400' : 'text-yellow-400'}`}>{syncMsg}</p>}

                        {/* Quick Navigation Links */}
                        {hasStats && activeTeam && (
                            <div className="mt-6 flex flex-col gap-3 pt-4 border-t border-gray-800">
                                <p className="text-xs font-semibold text-gray-500 uppercase tracking-widest mb-1">Portals</p>
                                <Link to={`/evaluator/${activeTeam}`}
                                    className="flex items-center justify-between bg-purple-900/40 hover:bg-purple-800/60 border border-purple-500/30 px-4 py-2.5 rounded-lg text-sm text-purple-300 transition-colors">
                                    <span className="flex items-center gap-2"><Star size={16} /> Judge Evaluator View</span>
                                    <ExternalLink size={16} className="opacity-50" />
                                </Link>
                                <Link to="/admin"
                                    className="flex items-center justify-between bg-neutral-900 overflow-hidden border border-neutral-700 hover:border-neutral-500 px-4 py-2.5 rounded-lg text-sm text-neutral-300 transition-colors">
                                    <span className="flex items-center gap-2"><Shield size={16} /> Admin Overwatch</span>
                                    <ExternalLink size={16} className="opacity-50" />
                                </Link>
                            </div>
                        )}
                    </div>

                    {hasStats ? (
                        <div className="bg-gray-900 border border-gray-800 p-6 rounded-2xl shadow-2xl relative overflow-hidden">
                            <div className="absolute top-0 right-0 p-4 opacity-10">
                                <Activity size={100} />
                            </div>
                            <h2 className="text-2xl font-bold mb-4 flex items-center gap-2">
                                <Code className="text-blue-400" /> AI Build Radar
                            </h2>
                            <div className="w-full bg-gray-800 rounded-full h-4 mb-4">
                                <div className="bg-gradient-to-r from-blue-500 to-[#9FEF00] h-4 rounded-full" style={{ width: `${aiData.relevanceScore}%` }}></div>
                            </div>
                            <p className="text-sm text-gray-400 mb-6">{aiData.relevanceScore}% Relevance Score vs Pitch</p>

                            <h3 className="font-semibold text-[#9FEF00] mb-2 flex items-center gap-2">Detected Operative Features</h3>
                            <ul className="space-y-2 mb-6">
                                {aiData.implementedFeatures.map((feat, idx) => (
                                    <li key={idx} className="bg-blue-900/20 text-blue-200 p-3 rounded-lg text-sm border border-blue-800/50">
                                        🚀 {feat}
                                    </li>
                                ))}
                            </ul>

                            <h3 className="font-semibold text-red-400 mb-2 flex items-center gap-2">Missing/Failing Pitch Claims</h3>
                            <ul className="space-y-2">
                                {aiData.missingPitchedFeatures.map((feat, idx) => (
                                    <li key={idx} className="bg-red-900/20 text-red-200 p-3 rounded-lg text-sm border border-red-800/50">
                                        ⚠️ {feat}
                                    </li>
                                ))}
                            </ul>
                        </div>
                    ) : (
                        <div className="bg-gray-900/50 border border-gray-800 p-6 rounded-2xl flex flex-col items-center justify-center text-center h-64 text-gray-500">
                            <Activity size={48} className="mb-4 opacity-50" />
                            <p>Awaiting Codebase Sync...</p>
                            <p className="text-xs mt-2">Link your repository above to generate AI Insights.</p>
                        </div>
                    )}

                    {/* Repository Summary & Branches */}
                    {hasStats && aiData.summary && (
                        <div className="bg-gray-900 border border-gray-800 p-6 rounded-2xl shadow-2xl">
                            <h2 className="text-xl font-bold mb-4 flex items-center gap-2 text-purple-400">
                                <Code size={20} /> Repository Analysis
                            </h2>
                            <div className="grid grid-cols-2 gap-4 mb-4">
                                <div className="bg-gray-800 p-3 rounded-lg">
                                    <p className="text-xs text-gray-400 uppercase">Total Features</p>
                                    <p className="text-2xl font-bold text-[#9FEF00]">{aiData.summary.totalFeatures}</p>
                                </div>
                                <div className="bg-gray-800 p-3 rounded-lg">
                                    <p className="text-xs text-gray-400 uppercase">Missing Claims</p>
                                    <p className="text-2xl font-bold text-red-400">{aiData.summary.missingFeatures}</p>
                                </div>
                                <div className="bg-gray-800 p-3 rounded-lg">
                                    <p className="text-xs text-gray-400 uppercase">Files Analyzed</p>
                                    <p className="text-2xl font-bold text-blue-400">{aiData.summary.fileCount}</p>
                                </div>
                                <div className="bg-gray-800 p-3 rounded-lg">
                                    <p className="text-xs text-gray-400 uppercase">Code Size</p>
                                    <p className="text-2xl font-bold text-purple-400">{(aiData.summary.codebaseSize / 1000).toFixed(0)}k</p>
                                </div>
                            </div>
                            
                            {githubData.branches && githubData.branches.length > 0 && (
                                <div className="mt-4">
                                    <h3 className="text-sm font-semibold text-gray-400 uppercase mb-2">
                                        Active Branches ({githubData.branches.length})
                                    </h3>
                                    <div className="flex flex-wrap gap-2">
                                        {githubData.branches.map((branch, idx) => (
                                            <span key={idx} className={`px-3 py-1 rounded-full text-xs font-mono ${branch.protected ? 'bg-green-900/30 text-green-300 border border-green-800/50' : 'bg-gray-800 text-gray-300 border border-gray-700'}`}>
                                                {branch.protected && '🔒 '}{branch.name}
                                            </span>
                                        ))}
                                    </div>
                                </div>
                            )}
                        </div>
                    )}
                </div>

                {/* Center/Right Column: Gamified Stats */}
                <div className="lg:col-span-2 space-y-8">

                    {hasStats ? (
                        <>
                            {/* Commit King / Feature Champion Banner */}
                            <div className="bg-gradient-to-r from-indigo-900 via-purple-900 to-gray-900 p-6 rounded-2xl border border-purple-500/30 flex items-center justify-between shadow-lg">
                                <div>
                                    <h2 className="text-xl text-purple-300 font-bold flex items-center gap-2 uppercase tracking-wide">
                                        <Award className="text-yellow-400" /> Crew Champion
                                    </h2>
                                    <p className="text-3xl font-extrabold text-white mt-1">{topCoder.author}</p>
                                    <p className="text-sm text-purple-200 mt-1 font-mono">
                                        {topCoder.featuresBuilt?.length || 0} features shipped • {topCoder.commits} commits pushed
                                    </p>
                                </div>
                                <motion.div animate={{ scale: [1, 1.1, 1] }} transition={{ repeat: Infinity, duration: 2 }}>
                                    <Flame size={64} className="text-yellow-500 drop-shadow-[0_0_15px_rgba(234,179,8,0.5)]" />
                                </motion.div>
                            </div>

                            {/* Graphical Telemetry */}
                            <div className="bg-gray-900 border border-gray-800 p-6 rounded-2xl shadow-2xl">
                                <h2 className="text-2xl font-bold mb-6 flex items-center gap-2 uppercase tracking-widest text-[#9FEF00]">
                                    Crew Contribution Matrix
                                </h2>

                                <div className="h-64 mb-8">
                                    <ResponsiveContainer width="100%" height="100%">
                                        <BarChart data={githubData.contributors}>
                                            <XAxis dataKey="author" stroke="#9ca3af" />
                                            <YAxis stroke="#9ca3af" />
                                            <Tooltip contentStyle={{ backgroundColor: '#111827', border: '1px solid #374151' }} />
                                            <Bar dataKey="commits" fill="#9FEF00" radius={[4, 4, 0, 0]} />
                                            <Bar dataKey="additions" fill="#3b82f6" stackId="a" />
                                            <Bar dataKey="deletions" fill="#ef4444" stackId="a" />
                                        </BarChart>
                                    </ResponsiveContainer>
                                </div>

                                {/* Peer Kudos Grid */}
                                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                                    {githubData.contributors.map(c => (
                                        <div key={c.author} className="flex flex-col items-center bg-gray-800 p-4 rounded-xl border border-gray-700 hover:border-blue-500 transition-colors">
                                            <img src={c.avatarUrl || "https://github.com/identicons/default.png"} alt={c.author} className="w-16 h-16 rounded-full mb-3 border-2 border-[#9FEF00]" />
                                            <span className="font-bold text-lg">{c.author}</span>
                                            <span className="text-xs text-gray-400">{c.additions} LOC added</span>

                                            {c.featuresBuilt && c.featuresBuilt.length > 0 ? (
                                                <div className="mt-3 mb-4 text-xs text-left w-full space-y-1">
                                                    <p className="text-blue-400 font-semibold mb-1 text-center border-b border-gray-700 pb-1">AI Attributed Code</p>
                                                    {c.featuresBuilt.map((feat, i) => (
                                                        <p key={i} className="text-gray-300 bg-gray-900 border border-gray-700 px-2 py-1 rounded truncate w-full" title={feat}>
                                                            ✨ {feat}
                                                        </p>
                                                    ))}
                                                </div>
                                            ) : (
                                                <div className="mt-3 mb-4 text-xs text-center text-gray-500 italic">No explicit features mapped yet</div>
                                            )}

                                            <button
                                                onClick={() => handleSpark(c.author)}
                                                className="flex items-center gap-2 bg-gradient-to-r from-orange-500 to-red-500 px-4 py-2 rounded-lg font-bold hover:scale-105 transition-transform"
                                            >
                                                <Zap size={16} />
                                                Give Spark ({sparksMap[c.author] || 0})
                                            </button>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </>
                    ) : null}

                    {/* Internal Crew Leaderboard (Always Visible once synced) */}
                    {hasStats && (
                        <div className="bg-gray-900 border border-gray-800 p-6 rounded-2xl shadow-2xl overflow-x-auto">
                            <h2 className="text-2xl font-bold mb-6 flex items-center gap-2 tracking-widest text-[#9FEF00] uppercase">
                                🏆 Crew Leaderboard <span className="text-xs text-gray-400 font-normal normal-case tracking-normal ml-2 border border-gray-700 px-2 py-1 rounded bg-black/30">Ranked by AI Verified Features</span>
                            </h2>
                            <table className="w-full text-left">
                                <thead>
                                    <tr className="border-b border-gray-800 text-gray-400 text-sm uppercase tracking-wider">
                                        <th className="pb-3 px-4">Rank</th>
                                        <th className="pb-3 px-4">Contributor</th>
                                        <th className="pb-3 px-4 hidden sm:table-cell">AI Code Mapping</th>
                                        <th className="pb-3 px-4">Commits</th>
                                        <th className="pb-3 px-4 hidden sm:table-cell">Impact (LOC)</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {githubData.contributors.map((c, idx) => (
                                        <tr key={c.author} className="border-b border-gray-800/50 hover:bg-gray-800/50 transition duration-150">
                                            <td className="py-4 px-4">
                                                <span className={`font-bold ${idx === 0 ? 'text-yellow-400 text-lg' : idx === 1 ? 'text-gray-300' : idx === 2 ? 'text-orange-400' : 'text-gray-500'}`}>
                                                    #{idx + 1}
                                                </span>
                                            </td>
                                            <td className="py-4 px-4 font-semibold text-white flex items-center gap-3">
                                                <img src={c.avatarUrl || "https://github.com/identicons/default.png"} alt={c.author} className="w-8 h-8 rounded-full border border-gray-700" />
                                                {c.author}
                                            </td>
                                            <td className="py-4 px-4 hidden sm:table-cell text-sm text-gray-400">
                                                {c.featuresBuilt && c.featuresBuilt.length > 0 ? (
                                                    <span className="bg-blue-900/30 text-blue-300 px-2 py-1 rounded-md text-xs border border-blue-800/50">
                                                        {c.featuresBuilt.length} Features Code
                                                    </span>
                                                ) : (
                                                    <span className="text-gray-600">—</span>
                                                )}
                                            </td>
                                            <td className="py-4 px-4 text-[#9FEF00] font-mono">{c.commits}</td>
                                            <td className="py-4 px-4 hidden sm:table-cell">
                                                <span className="text-blue-400 text-xs mr-2">+{c.additions}</span>
                                                <span className="text-red-400 text-xs">-{c.deletions}</span>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
